name: Unity CI

on:
  push:
    branches: [main, develop, feature/**]
  pull_request:

env:
  UNITY_VERSION: 6000.0.38f1

jobs:
  test-editmode:
    name: Test in Edit Mode
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-Test-${{ env.UNITY_VERSION }}
          restore-keys: Library-Test-
      - uses: game-ci/unity-test-runner@v3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: .
          testMode: editmode
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          customImage: unityci/editor:6000.0.38f1-linux-il2cpp-1
          customParameters: -nographics

  test-playmode:
    name: Test in Play Mode
    needs: test-editmode
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-Test-${{ env.UNITY_VERSION }}
          restore-keys: Library-Test-
      - uses: game-ci/unity-test-runner@v3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: .
          testMode: playmode
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          customImage: unityci/editor:6000.0.38f1-linux-il2cpp-1
          customParameters: -nographics

  buildForSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    needs: test-playmode
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
          targetPlatform: ${{ matrix.targetPlatform }}
          customImage: unityci/editor:6000.0.38f1-linux-il2cpp-1
      - uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
