name: unity-ci

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:

jobs:
  build-windows:
    name: Build Windows Standalone (IL2CPP)
    runs-on: ubuntu-latest
    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_VERSION: 6000.0.38f1
    steps:
      - uses: actions/checkout@v4

      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('ProjectSettings/ProjectVersion.txt') }}-${{ hashFiles('Packages/manifest.json') }}
          restore-keys: |
            Library-

      - name: Build StandaloneWindows64
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: StandaloneWindows64
          unityVersion: ${{ env.UNITY_VERSION }}

      - name: Compress build artefact
        run: |
          cd Build/StandaloneWindows64
          zip -r -9 -m ../../Build-StandaloneWindows64.zip .
          cd ../..
          sha256sum Build-StandaloneWindows64.zip > Build-StandaloneWindows64.sha256

      - name: Publish to GitHub Releases
        if: ${{ github.ref_type == 'tag' }}
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            Build-StandaloneWindows64.zip
            Build-StandaloneWindows64.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  tests:
    needs: build-windows
    runs-on: ubuntu-latest
    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_VERSION: 6000.0.38f1
    steps:
      - uses: actions/checkout@v4
      - name: Run PlayMode tests
        uses: game-ci/unity-test-runner@v4
        with:
          testMode: PlayMode
          artifactsPath: TestResults
          unityVersion: ${{ env.UNITY_VERSION }}
